config/routes.rb
Rails.application.routes.draw do
  
  root 'knots#index'
  resources :knots do
    post 'fileupload'
  end
  
  get 'sessions/login'
  get 'sessions/logout'
  post 'sessions/create'

end

app/models/attatch.rb
class Attatch < ActiveRecord::Base
	belongs_to :knot

	has_attached_file :file, styles: { medium: "480x480>", thumb: "150x150>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :file, content_type: /\Aimage\/.*\Z/
end

app/models/knot.rb
class Knot < ActiveRecord::Base
	attr_accessor :knots

	has_many :relations_to, :foreign_key => "knot_id", :class_name => "Relationship"
	has_many :relations_from, :foreign_key => "piece_id", :class_name => "Relationship"

	has_many :linked_to, :through => :relations_to, :source => :piece
	has_many :linked_from, :through => :relations_from, :source => :knot

	has_many :attatch
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :knot, :foreign_key => "knot_id", :class_name => "Knot"
	belongs_to :piece, :foreign_key => "piece_id", :class_name => "Knot"
end

app/models/session.rb
require 'bcrypt'

class Session < ActiveRecord::Base
	def password
		@password ||= BCrypt::Password.new(self.password_digest)
	end

	def password=(newPassword)
		@password = BCrypt::Password.create(newPassword)
		self.password_digest = @password
	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/knots_controller.rb
class KnotsController < ApplicationController
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :set_knot, only: [:show, :edit, :update, :destroy]
  before_action :login_check, only: [:create, :update, :destroy]

  # GET /knots
  # GET /knots.json
  def index
    @knots = Knot.order('updated_at DESC').all
  end

  # GET /knots/1
  # GET /knots/1.json
  def show
    @attatch = Attatch.new
    @uploadeds = Attatch.where(knot_id:params[:id]).order(:created_at)
    @knot.content = parse(@knot.content)
    for a in @uploadeds
      print "uploaded: ", a.file.url(:mediam)
    end
  end


  def fileupload

    params[:attatch][:files].each do |file|
      @attatch = Attatch.new(file: file)
      @attatch.knot_id = params[:knot_id]
      if @attatch.save
        flash[:success] = "fileupload ok."
      else
        flash[:success] = "fileupload fail."
      end
    end

    redirect_to knot_path(params[:knot_id])
  end

  # GET /knots/new
  def new
    @knot = Knot.new
  end

  # GET /knots/1/edit
  def edit
  end

  # POST /knots
  # POST /knots.json
  def create
    @knot = Knot.new(knot_params)
    if @knot.name.blank?
      @knot.name = Time.now.strftime("%Y%m%d%H%M%S").gsub(/0/, 'o')
    end 

    respond_to do |format|
      if updateRelation(knot_params) && @knot.save
        format.html { redirect_to @knot, notice: 'Knot was successfully created.' }
        format.json { render :show, status: :created, location: @knot }
      else
        format.html { render :new }
        format.json { render json: @knot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /knots/1
  # PATCH/PUT /knots/1.json
  def update
    respond_to do |format|
      if updateRelation(knot_params) && @knot.update(knot_params)
        format.html { redirect_to @knot, notice: 'Knot was successfully updated.' }
        format.json { render :show, status: :ok, location: @knot }
      else
        format.html { render :edit }
        format.json { render json: @knot.errors, status: :unprocessable_entity }
      end
    end
  end

  def updateRelation(knot_params)
    begin
      items = []
      knot_params[:knots].split(/[,\s]+/).each do |p|
        k = Knot.find_by name:p
        items.push(k)
      end

      @knot.linked_from = items
      
    rescue
      false
    ensure
      true
    end
    
  end

  # DELETE /knots/1
  # DELETE /knots/1.json
  def destroy
    @knot.destroy
    respond_to do |format|
      format.html { redirect_to knots_url, notice: 'Knot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_knot
    @knot = Knot.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def knot_params
    params.require(:knot).permit(:name, :content, :knots)
  end

  def login_check
    if !isLogined()
      raise "session error"
    end
  end

  def attatch_params
    params.require(:attatch).permit(:file)
  end

  def parse(content)
    parsed = ''
    isNoneBreakBlock = false
    isCodeBlock = false
    codeBlockContent = ''
    codeBlockName = ''

    content.split(/\n/).each do |line|
      line.gsub! /\s+$/, ''

      if isCodeBlock 
        if line =~ /^```(.*)?$/
          lexer = Rouge::Lexer.find codeBlockName
          if lexer 
            source = codeBlockContent
            formatter = Rouge::Formatters::HTML.new(css_class: 'highlight')
            parsed += formatter.format(lexer.lex(source))
          else
            parsed += '<div class="codeblock"><pre>' + "\n\n"
            parsed += codeBlockContent
            parsed += '</pre></div>'
          end

          isCodeBlock = false
          codeBlockContent = ''
          codeBlockName = ''
          next
        else
          codeBlockContent += line + "\n"
          next
        end
      else
        if line =~ /^```(.*)?$/
          codeBlockName = $1
          isCodeBlock = true
          next
        end
      end

      line.strip!

      if line =~ /^"""/
        isNoneBreakBlock = isNoneBreakBlock ? false : true
        next
      end

      if line =~ /^---/
        parsed += "<hr />"
        next
      end
        
      if line =~ /^(\={1,5})(.*)$/
        parsed += "<h#{$1.to_s.length}>#{$2}</h#{$1.to_s.length}>"
        next
      end

      if /``(?<code>.*?)``/ =~ line
        line = "#{special($`)}<span class=\"codeline\">#{safeHtml(code)}</span>#{special($')}"
        line += "<br />" unless isNoneBreakBlock
        parsed += line + "\n"
        next
      end

      if line =~ /@img (.*?)@/
        att = Attatch.where(file_file_name:"#{$1}")
        begin
          parsed += "<img src=\"#{att[0].file.url(:medium)}\" />"
        rescue
          parsed += "no file."
        end
        next
      end

      special line

      if line =~ /\(\((?:(.*?)(?: (.*?))?)\)\)/
        rs = Extension.new(@config).build($1, $2)
        line.gsub! $&, rs
      end

      line += "<br />" unless isNoneBreakBlock

      parsed += line + "\n"
    end

    parsed
  end 

  def special str
    str.gsub! /''(.*?)''/, "<strong>\\1</strong>"
    str.gsub! /__(.*?)__/, "<u>\\1</u>"
    str.gsub! /\/\/(.*?)\/\//, "<i>\\1</i>" 
    str.gsub! /~~(.*?)~~/, "<del>\\1</del>"
    str
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  protect_from_forgery with: :exception
  include SessionsHelper

  def login
    @session = Session.new
  end

  def create
    @user = Session.find_by user:session_params[:user]

    if @user && @user.password == session_params[:password]
      reset_session
      session[:user] = @user.user

      respond_to do |format|
        format.html { redirect_to root_url, notice: 'login successed.' }
        format.json { head :no_content }
      end      
    else
      respond_to do |format|
        format.html { redirect_to sessions_login_url, notice: 'login failed.' }
        format.json { head :no_content }
      end
    end
  end

  def logout
    session.clear
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'bye bye.' }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
  def session_params
      params.require(:session).permit(:user, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_user
		@current_user ||= Session.find_by user:session[:user]
	end

	def loged_in
		!current_user.nil?
	end
	
	def zeroToO(datetime) 
		datetime.to_s.gsub(/[^0-9]/, "").gsub(/0/, "o")
	end
end

app/helpers/knots_helper.rb
module KnotsHelper

	def knots_s(knot)
		r = []
		knot.linked_from.each do |p|
			r << p.name
		end
		r.join(", ")
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def isLogined()
		session[:user] != nil
	end

end

app/views/knots/_form.html.erb
<%= simple_form_for @knot do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :content, :as => "text", input_html: { rows: 15 } %>
    <%= f.input :knots, input_html: { value: knots_s(@knot) } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>	
  </div>
<% end %>


<script>
$(document).ready(function(){
	// overrite 'form-control' class
	$('input, textarea').css('background-color', '#000').css('color', '#bbb').css('border-color', '#333');
});
</script>

app/views/knots/edit.html.erb
<h1>Editing Knot</h1>

<%= render 'form' %>

<%= link_to '', @knot, data: { keybinding: 'ctrl+c' } %>

app/views/knots/index.html.erb
<div class="knot">
    <span class="ring">recent changes</span>
    <br /><br />
    <% @knots.each do |knot| %>
        <small>
        <% knot.linked_from.each do |p| %>
        <span class="up"><%= link_to p.name, knot_path(p) %></span>
        <% end %>
        </small>
        <span class="ring"><%= link_to knot.name, knot %></span>
        <span class="datetime"><%= zeroToO(knot.created_at) %></span>
        <br />    

    <% end %>


</div>

app/views/knots/new.html.erb
<h1>New Knot</h1>

<%= render 'form' %>

app/views/knots/show.html.erb
<div class="knot">
	
	<h5 class="ring">
		<small><% @knot.linked_from.each do |k| %><span class="ring"><%= link_to k.name, knot_path(k) %></span>. <% end %></small>
		<%= @knot.name %>
	</h5>

	<br />

	<p><%= @knot.content.html_safe %></p>

	<p class="text-right">
		<% @knot.linked_to.each do |k| %>
		<span class="ring"><%= link_to k.name, knot_path(k) %></span> <span class="datetime"><%= zeroToO(k.created_at) %></span><br />
	    <% end %>
	</p>

	
	<p class="datetime"><%= zeroToO(@knot.created_at) %></p>

	<% if isLogined  %>
	<%= link_to '', edit_knot_path(@knot), data: { keybinding: 'ctrl+e' } %>

	<%= form_for @attatch, url: knot_fileupload_path(@knot), html: { multipart: true } do |form| %>
	  <%= form.file_field :files, multiple: true %>
	  <a href="#" class="fileupload"><span class="glyphicon glyphicon-upload" aria-hidden="true"></span></a>
	<% end %>


	<script>
	$('.fileupload').click(function(){
		$('input[type=file]').click();	
	});

	$('input[type=file]').change(function(){
		$(this).parent('form').submit();
	}).css('display', 'none');
	</script>
	
	<hr />

	<ul>
	<% @uploadeds.each do |uploaded| %>
		<li><small>@img <%= uploaded.file.path(:medium).gsub(/.*\//, '') %>@</small></li>
	<% end %>
	</ul>

	<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>knot</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

<body>
  

  <div class="container">
    <div class="logo">
      <h3 class="title"><span style="font-size:50pt"><%= link_to 'M@', root_path %></span></h3>
    </div>

      <!-- <div class="header clearfix">
      </div> -->

      <%= yield %>

      <hr>

      <footer class="footer">
        <p>&copy;trunkcat.com 2015 <i>powered by <%= link_to 'knot', root_path %></i></p>
        <p></p>
        <p class="text-right">
          <% if isLogined %> 
          <strong><%= current_user.user %></strong> 
          <a href="/sessions/logout"><span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></a>
          <% end %>
        </p>      
      </footer>

    </div> <!-- /container -->

    
    <%= link_to '', root_path, data: { keybinding: 'ctrl+m' } %>
    
    <% if isLogined  %>
    <%= link_to '', new_knot_path, data: { keybinding: 'ctrl+n' } %>
    <%= link_to '', sessions_logout_path, data: { keybinding: 'ctrl+l ctrl+o' } %>
    <% end %>
    <% if !isLogined  %>
    <%= link_to '', sessions_login_path, data: { keybinding: 'ctrl+l ctrl+i' } %>
    <% end %>



    
    
</body>
</html>